name: Chainguard Registry Example

# Set up some kind of cron job
on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write  # This is needed for OIDC federation.

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: chainguard-dev/setup-chainctl@main
        with:
          identity: ${{ secrets.CGIDENTITY }}
      - uses: imjasonh/setup-crane@v0.3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
     
     # Bash
      - run: | 
          LENGTH=$(($(chainctl images list --parent ${{ secrets.ORG_NAME }} -o json | jq '. | length')-1))

          IMAGES=($(chainctl images list --parent ${{ secrets.ORG_NAME }} -o json | jq -r '.[] | "\(.repo.name):\(.tags[].name)"'))
  
          for image in "${IMAGES[@]}"; do
            source_image="cgr.dev/${{ secrets.ORG_NAME }}/${image}"
            target_image="ghcr.io/metalstormbass/${image}"
            crane copy ${source_image} ${target_image}
          done
        